name: CI

on:
  push:
    branches: [ "main", "desenvolvimento" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4

      - name: Verificar arquivos do repositorio
        run: |
          echo "Executando validacao do projeto..."
          ls -la
          test -f projeto.txt
          echo "Arquivo projeto.txt encontrado com sucesso."